# Site settings 配置站点
title: '⌘鸡哥⌘的博客'
description: 'Just for fun !'
keyword: '徐金琦, 徐金琦的独立博客, 徐金琦的博客, 前端,  前端博客, javascript, 操作系统, ubuntu, 网络'
url: 'https://xukimseven.github.io' # your host

# 博主
author: 'talkCock'

# 分页
paginate: 6
paginatepath: ['page:num']

# since
footer:
  since: 2018

# nav 中文字符空格：&emsp;
nav:
  首页: '/'
  标签: '/tags.html'
  # 关于鸡哥: '/about.html'
  关于鸡哥: '/resume/index.html'
  友情链接: '/friendLink.html'

# 网站是否需要搜索
search: true

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮
highlighter: rouge
